GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/687685e7a6b070b41a0d3831

###
DELETE http://localhost:3001/api/persons/6877efeec3c3791fc9e073b1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Gonçalo",
    "number": "123456789"
}
