GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvbmNhbG8iLCJpZCI6IjY4OGUxYjkxNWE5ZDJmMTdmMGJhZjdmNSIsImlhdCI6MTc1Njg5NzgxOX0.jsIefNmuLT2dpYnRjN0YxpTPIFz7HdbOT3Vj7s662Nw

{
    "title": "The Power of Three.js",
    "author": "Ferid Brković",
    "url": "https://javascript.plainenglish.io/the-power-of-three-js-4cbc489c2a73",
    "likes": 182,
    "comments": ["i've done a lot of cool stuff with three.js"]
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Matti Luukkainen",
    "username": "mluukkai",
    "password": "secret"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Gonçalo",
    "username": "goncalo",
    "password": "segredo"
}

###
GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "secret"
}

###

DELETE http://localhost:3003/api/blogs/6888f59e0f37655eefc9f01f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODg4ZDQwODAzMzRjZDYxOGRhZjYwYjYiLCJpYXQiOjE3NTM4MDYyMjF9.kSqFo_LYYifc8BbG5Cr1sOe9AZV1AXtsI0UuEWsAfzQ
