GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODg4ZDQwODAzMzRjZDYxOGRhZjYwYjYiLCJpYXQiOjE3NTM4MDE3MDJ9.77jc2FCWP0qWodlBw0MP9YYg6YnN8Ga4RUu9Wih9W2Y

{
    "title": "Fullstack development is cool!",
    "author": "Someone",
    "url": "something.com",
    "likes": 1000
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Matti Luukkainen",
    "username": "mluukkai",
    "password": "secretpassword"
}

###
GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "secretpassword"
}